//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.07 at 08:27:12 p. m. COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.servicios.co/pagos/schemas", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package co.microservices.wsdl;
