//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.07 at 01:00:56 a. m. COT 
//


package co.microservices.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Pago complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Pago">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="referenciaFactura" type="{http://www.servicios.co/pagos/schemas}ReferenciaFactura"/>
 *         &lt;element name="totalPagar" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Pago", propOrder = {
    "referenciaFactura",
    "totalPagar"
})
public class Pago {

    @XmlElement(required = true)
    protected ReferenciaFactura referenciaFactura;
    protected double totalPagar;

    /**
     * Gets the value of the referenciaFactura property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenciaFactura }
     *     
     */
    public ReferenciaFactura getReferenciaFactura() {
        return referenciaFactura;
    }

    /**
     * Sets the value of the referenciaFactura property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenciaFactura }
     *     
     */
    public void setReferenciaFactura(ReferenciaFactura value) {
        this.referenciaFactura = value;
    }

    /**
     * Gets the value of the totalPagar property.
     * 
     */
    public double getTotalPagar() {
        return totalPagar;
    }

    /**
     * Sets the value of the totalPagar property.
     * 
     */
    public void setTotalPagar(double value) {
        this.totalPagar = value;
    }

}
